spring.datasource.url=jdbc:postgresql://localhost:5433/plantcare
spring.datasource.username=postgres
spring.datasource.password=PlantCare2026!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect